# This file should not be modified as it may get changed by the maintainer.
# Add extra configuration files to the extra_config_files directory to override
# the settings in this file

# Directory in which to place config overrides
extra_config_files: /etc/wazo-stat/conf.d/

# Change the log level to debug level.
debug: false

# Log file.
log_filename: /var/log/wazo-stat.log

# Database connection settings.
db_uri: postgresql://asterisk:proformatique@localhost/asterisk?application_name=wazo-stat

# wazo-auth connection settings.
auth:
  host: localhost
  port: 9497
  prefix: null
  https: false

# wazo-confd connection settings
confd:
  host: localhost
  port: 9486
  prefix: null
  https: false
